server {
    listen 80;

    location /api/ {
        proxy_pass http://flask-app:5000;
    }

    location /health {
        proxy_pass http://flask-app:5000;
    }

    location / {
        return 404 "not found\n";
    }
}
